workers_dev = true
name = "inw"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]
main = "./worker.ts"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "inw"
database_id = "007cf749-c9d3-4080-b9f4-c2caf2e63987"
migrations_dir = "drizzle"
